// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio3._1.Migrations
{
    [DbContext(typeof(ConsultorioDbContext))]
    partial class ConsultorioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consulta", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("horaFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("horaInicial")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("cpf");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cpf");

                    b.ToTable("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
